### PR TITLE
Remove depreciated stream API for Webkit compatability

### PR DESCRIPTION
**Pull request by digitaldan**
Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by florian-h05** [comment]
Did you test?
I am asking because if yes, I will merge without testing myself and then install the artifact from Jenkins to test my setup.

**Comment by digitaldan** [comment]
Yes, works on both IOS and Safari/Mac

**Comment by florian-h05** [comment]
Okay 👍 
Still working on Android and Windows?

**Comment by digitaldan** [comment]
tested on chrome on mac and android, i'm confident windows works as well as the chrome code bases does not differ in this regard.

**Pull request merged**
